name: C/C++ CI

on:
  push:
    branches: [ renova ]
  pull_request:
    branches: [ renova ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      database:
        image: mysql:5.7
        env: 
          MYSQL_DATABASE: ragnarok
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306
    steps:
      - uses: actions/checkout@v2
      - name: Find and replace database host
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "database"
          replace: "127.0.0.1"
          include:  "conf/import-tmpl/inter_conf.txt"
      - name: Configure rAthena
        run: ./configure --enable-prere=no --enable-vip=no --enable-buildbot=yes
      - name: Copy NPCs
        run: ./tools/ci/npc.sh
      - name: Clean
        run: make clean
      - name: Make rAthena
        run: make all
      - name: Configure MySQL
        run: | 
          sudo /etc/init.d/mysql start
          mysql -h 127.0.0.1 --port ${{ job.services.database.ports['3306'] }} -u root -ppassword -e "CREATE USER 'rangarok'@'%' IDENTIFIED WITH mysql_native_password BY 'ragnarok';";
          mysql -h 127.0.0.1 --port ${{ job.services.database.ports['3306'] }} -u root -ppassword -e "USE ragnarok; GRANT ALL PRIVILEGES ON ragnarok.* TO 'ragnarok'@'%';";
      - name: Test Servers
        run: |
          ./login-server --run-once
          ./char-server --run-once
          ./map-server --run-once
